steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '--tag'
  - 'gcr.io/$PROJECT_ID/dms-frontend:latest'
  - '--build-arg'
  - 'PROJECT_ID=$PROJECT_ID'
  - '--build-arg'
  - 'REGION=us-central1'
  - '.'
images:
- 'gcr.io/$PROJECT_ID/dms-frontend:latest'
