steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/migration-demo-429608/dms-backend:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/migration-demo-429608/dms-backend:latest']
images:
- 'gcr.io/migration-demo-429608/dms-backend:latest'
